apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: ${{ values.component_id }}-listener
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  serviceAccountName: pipeline
  triggers:
    - name: gitlab-push
      interceptors:
        - ref:
            name: gitlab
          params:
            - name: secretRef
              value:
                secretName: webhook-secret
                secretKey: token
            - name: eventTypes
              value:
                - Push Hook
        - ref:
            name: cel
          params:
            - name: filter
              value: >-
                body.commits.exists(c,
                  c.added.exists(f, f.startsWith('parasol-chat/')) ||
                  c.modified.exists(f, f.startsWith('parasol-chat/')) ||
                  c.removed.exists(f, f.startsWith('parasol-chat/'))
                )
      bindings:
        - ref: ${{ values.component_id }}-gitlab-binding
      template:
        ref: ${{ values.component_id }}-build-template
