apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: ${{ values.component_id }}-build-run
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    tekton.dev/pipeline: ${{ values.component_id }}-build
spec:
  pipelineRef:
    name: ${{ values.component_id }}-build
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
