apiVersion: v1
kind: Service
metadata:
  name: ${{ values.component_id }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app: ${{ values.component_id }}
    backstage.io/kubernetes-id: ${{ values.component_id }}
spec:
  selector:
    app: ${{ values.component_id }}
  ports:
    - port: 8501
      targetPort: 8501
      protocol: TCP
      name: http
