apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: ${{ values.component_id }}-gitlab-binding
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    backstage.io/kubernetes-id: ${{ values.component_id }}
spec:
  params:
    - name: git-url
      value: $(body.repository.git_http_url)
    - name: git-revision
      value: $(body.checkout_sha)
